/**
 * TC-COUPON-001 — View and Activate Earned Coupon
 *
 * Requirement: FR-8 – Coupon Viewing and Activation
 * Priority:    Medium
 * Type:        Positive + Negative
 *
 * Pre-condition: A coupon is generated by completing a claim (FOUND item flow).
 *
 * Tests:
 *   1. User with an earned coupon can fetch it via GET /api/coupons/
 *   2. User can activate an available coupon via POST /api/coupons/activate/
 *   3. Already-activated (redeemed) coupon cannot be activated again (400)
 *   4. A user cannot activate another user's coupon (404)
 */
import { test, expect } from '../fixtures/auth.fixture'
import {
  registerUser,
  loginUser,
  createItem,
  deleteItem,
  fetchCategories,
  fetchLocations,
  approveItem,
  createClaim,
  updateClaimStatus,
  fetchUserCoupons,
  activateCoupon,
} from '../helpers/api.helpers'
import { uniqueEmail, STRONG_PASSWORD, ADMIN_CREDENTIALS } from '../fixtures/test-data'

const API_BASE = 'http://127.0.0.1:8000'

test.describe('TC-COUPON-001: View and Activate Coupon', () => {
  let adminToken: string
  let finderToken: string
  let claimantToken: string
  let strangerToken: string

  let foundItemId: number
  let couponCode: string

  test.beforeAll(async ({ request }) => {
    try {
      await registerUser(request, {
        email: ADMIN_CREDENTIALS.email,
        full_name: ADMIN_CREDENTIALS.full_name,
        password: ADMIN_CREDENTIALS.password,
        password_confirm: ADMIN_CREDENTIALS.password,
        role: 'admin',
      })
    } catch { /* already exists */ }
    const adminLogin = await loginUser(request, ADMIN_CREDENTIALS.email, ADMIN_CREDENTIALS.password)
    adminToken = adminLogin.access

    const finderReg = await registerUser(request, {
      email: uniqueEmail('coupon-act-finder'),
      full_name: 'Coupon Activate Finder',
      password: STRONG_PASSWORD,
      password_confirm: STRONG_PASSWORD,
    })
    finderToken = finderReg.tokens.access

    const claimantReg = await registerUser(request, {
      email: uniqueEmail('coupon-act-claimant'),
      full_name: 'Coupon Activate Claimant',
      password: STRONG_PASSWORD,
      password_confirm: STRONG_PASSWORD,
    })
    claimantToken = claimantReg.tokens.access

    const strangerReg = await registerUser(request, {
      email: uniqueEmail('coupon-act-stranger'),
      full_name: 'Coupon Activate Stranger',
      password: STRONG_PASSWORD,
      password_confirm: STRONG_PASSWORD,
    })
    strangerToken = strangerReg.tokens.access

    // Create a completed FOUND item claim → finder earns a coupon
    const categories = await fetchCategories(request, finderToken)
    const locations = await fetchLocations(request, finderToken)
    const item = await createItem(request, finderToken, {
      title: `E2E Coupon Activate ${Date.now()}`,
      description: 'Found item for coupon activation tests',
      item_type: 'found',
      category: categories[0].id,
      location: locations[0].id,
    })
    foundItemId = item.id
    await approveItem(request, adminToken, foundItemId)
    const claim = await createClaim(request, claimantToken, {
      item: foundItemId,
      message: 'This is mine',
    })
    await updateClaimStatus(request, adminToken, claim.id, 'approved')
    await updateClaimStatus(request, adminToken, claim.id, 'completed')

    // Retrieve the coupon code issued to the finder
    const coupons = await fetchUserCoupons(request, finderToken)
    couponCode = coupons[0].code
  })

  test.afterAll(async ({ request }) => {
    try { await deleteItem(request, finderToken, foundItemId) } catch { /* best-effort */ }
  })

  test('finder can fetch their earned coupon via GET /api/coupons/', async ({ request }) => {
    const coupons = await fetchUserCoupons(request, finderToken)
    expect(coupons.length).toBeGreaterThanOrEqual(1)
    expect(coupons[0].code).toBeTruthy()
    expect(coupons[0].is_redeemed).toBe(false)
    expect(coupons[0].expires_at).toBeTruthy()
  })

  test('finder can activate their coupon → is_redeemed becomes true', async ({ request }) => {
    const result = await activateCoupon(request, finderToken, couponCode)
    expect(result.message).toBeTruthy()

    // Verify via list endpoint that the coupon is now redeemed
    const coupons = await fetchUserCoupons(request, finderToken)
    const activated = coupons.find((c: { code: string }) => c.code === couponCode)
    expect(activated).toBeTruthy()
    expect((activated as { is_redeemed: boolean }).is_redeemed).toBe(true)
  })

  test('already-redeemed coupon cannot be activated again (400)', async ({ request }) => {
    // couponCode is redeemed from the previous test; second attempt must fail
    const res = await request.post(`${API_BASE}/api/coupons/activate/`, {
      headers: { Authorization: `Bearer ${finderToken}` },
      data: { code: couponCode },
    })
    expect(res.status()).toBe(400)
  })

  test('stranger cannot activate another user\'s coupon (404)', async ({ request }) => {
    const res = await request.post(`${API_BASE}/api/coupons/activate/`, {
      headers: { Authorization: `Bearer ${strangerToken}` },
      data: { code: couponCode },
    })
    expect(res.status()).toBe(404)
  })
})
